#ifndef CMN_INCLUDED
#define CMN_INCLUDED

// some var defination
#define COLUMN_NUM 12
#define COLUMNS (char*[12]) { "id", "published", "updated", "title", "content", "author", "keyword", "favoriate", "view", "duration", "category", "src" }

// parser -> init
typedef struct Init_Struct {
    char *match_str;       // Data of matching string. Pattern: A or A|B|C or +A,-B,+C
    char *query_mode;      // Define the query mode('single_word', 'boolean' or 'multiterm').
    char *rank_mode;       // Define the ranking mode('asc' or 'desc').
    char *match_mode;      // Define the match mode(prefix or word).
    char *begin_at;        // The column that each record begins at.
    char **output_column;  // Define the output column.
    int output_column_num; // Number of the output column.
    float error_rate;      // Define the lower bound of tolerable error rate.
    int insensitive;       // Is insensitive to alpha case?
    int output_size;       // Define the output size.
    int output_length;     // The length of output record.
} InitOpt;

// init -> jobControl
typedef struct Job_Ctl_Struct {
    char **match_strs;     // 2-Dim array of string.
    char *match_relations; // store the additional flags of matching(Ex ['|', '&'], ['-', '+'])
    char *match_mode;
    char *begin_at;
    float error_rate;
    int insensitive;
    int match_str_num;    // number of contained strings
} JobOpt;

// jobControl -> threadCtl
typedef struct Thread_Ctl_Struct {
    char **match_strs;
    char *match_relations;
    char *match_mode;
    char *begin_at;
    float error_rate;
    int match_str_num;
    int insensitive;
} ThreadOpt;

// threadCtl -> matching
// Ps: matching: threadId = 1~255, scoring: threadId = 0.
// 1. Control flags
typedef struct Matching_Opt {
    // for matching
    char **match_strs;
    char *match_mode;
    float error_rate;
    int match_str_num;
    int insensitive;

    // for scoring
    char *match_relations;
} MatchOpt;
// 2. Data
typedef struct Matching_Base {
    char ***sample_records;    // All of the sample records.
    int record_num;
} MatchBase;

// Each record has one of this structure, generated by them thread.
typedef struct Result_Record {
    char **record;
    int score;
} ResultRec;

// matching -> threadCtl
typedef struct Matching_Result {
    ResultRec **result_records; // All of the result records
    int result_length;
} MatchRes;

// threadCtl -> ranker(scorer)
typedef struct Ranking_info {
    ResultRec **result_records;
    int result_length;
    char *rank_mode;
} RankInfo;

// ranker -> packer
typedef struct Packing_Info {
    ResultRec **result_records;
    char **output_column;
    int output_column_num;
    int output_size;
    int output_length;
} PackInfo;

// packer -> outpur
typedef struct Result {
    ResultRec **result_records;
    char **result_column;
    int result_length;
    int result_column_num;
} Result;

#endif
